### ISSUE TITLE
Crashing in xaml files

### ISSUE THREAD

**Issue by ziomek64** [azemoh/vs-one-monokai#1]
Hello,
I don't know why but it's crashing for me in xaml files. I'm xamarin developer so i really need it, and this theme is just beautiful.

**Comment by azemoh** [comment]
Hey @ziomek64, thanks for reporting this. I just published a release with a fix, can you please update the theme and let me know how it goes? Thanks!

**Comment by ziomek64** [comment]
It is working, thank you! Looks good too

**Comment by azemoh** [comment]
Thanks!
