### ISSUE TITLE
Syntax Highlighting Issues with C# since 17.9.0 Update

### ISSUE THREAD

**Issue by ireth92** [azemoh/vs-one-monokai#8]
After updating to Visual Studio 2022 version 17.9.0, there are several syntax highlighting issues in C# files within Unity projects. I've noticed the following elements that are no longer colored:
- Directives and Instance references (appear white instead of blue)
- Method calls (appear white instead of green)

**Comment by MahdiyarGHD** [comment]
yeah syntax highlighting is not functioning properly in the 17.9.0 update.

**Comment by att1008** [comment]
Change "Tools"-> "Options"-> "Fonts and Colors"-> "Text Editor"-> "Identifier" to the default value if it is automatic and the default value if it is automatic

**Comment by ireth92** [comment]
I changed the Identifier from default to automatic, and that actually did the trick. Thanks @att1008 !
