### ISSUE TITLE
VS 2022 17.9.2 - Identifier and Variable coloring not functioning

### ISSUE THREAD

**Issue by Veloxtus** [azemoh/vs-one-monokai#9]
After updating, the One Monokai Theme does not properly color multiple aspects of text within the editor appropriately.

This issue from 2 weeks ago does not resolve this issue (Changing the Fonts and Colors > Text Editor > Identifier > Default) as even on Default the colors are not correct.

Validated through clearing all cached settings and reinstalling One Monokai.

Attached Screenshots of the outcome.
![Screenshot 2024-02-29 005130](https://github.com/azemoh/vs-one-monokai/assets/30667690/22fe6509-7f0e-49c2-8b6c-7d95fb99d732)
![Screenshot 2024-02-29 004930](https://github.com/azemoh/vs-one-monokai/assets/30667690/7f89438c-7581-4170-830e-9f8ed3ddf9c8)

**Comment by att1008** [comment]
Change identifier to automatic

**Comment by Veloxtus** [comment]
Removed
